/**
 * WinSuite & MacSuite v6.3 - Immutable Command Allowlist
 * Strict isolation: only predefined commands with predefined executables and fixed arguments
 * are permitted to execute.
 */

export const COMMAND_ALLOWLIST = {
  // ── Windows Commands ────────────────────────────────────────────────────────
  'win.sfc': {
    platform: 'windows',
    bin: 'sfc',
    fixedArgs: ['/scannow'],
    risk: 'moderate',
    requiresElevation: true,
    requiresConfirmation: false,
    timeoutMs: 600000, // 10 minutes
    reversible: true,
    description: 'System File Checker (sfc /scannow)',
    verifyMethod: 'sfc_status',
  },
  'win.dism.health': {
    platform: 'windows',
    bin: 'dism',
    fixedArgs: ['/Online', '/Cleanup-Image', '/RestoreHealth'],
    risk: 'moderate',
    requiresElevation: true,
    requiresConfirmation: false,
    timeoutMs: 600000,
    reversible: true,
    description: 'DISM Component Store Health Repair',
    verifyMethod: 'dism_status',
  },
  'win.dism.cleanup': {
    platform: 'windows',
    bin: 'dism',
    fixedArgs: ['/Online', '/Cleanup-Image', '/StartComponentCleanup'],
    risk: 'moderate',
    requiresElevation: true,
    requiresConfirmation: false,
    timeoutMs: 600000,
    reversible: false,
    description: 'DISM Component Store Cleanup',
    verifyMethod: 'dism_status',
  },
  'win.winget.upgrade': {
    platform: 'windows',
    bin: 'winget',
    fixedArgs: ['upgrade', '--all', '--accept-source-agreements', '--accept-package-agreements', '--silent'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 300000,
    reversible: true,
    description: 'Upgrade All Winget Packages',
    verifyMethod: 'winget_status',
  },
  'win.flushdns': {
    platform: 'windows',
    bin: 'ipconfig',
    fixedArgs: ['/flushdns'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 15000,
    reversible: true,
    description: 'Flush DNS Resolver Cache',
    verifyMethod: 'none',
  },
  'win.defender.update': {
    platform: 'windows',
    bin: 'powershell',
    fixedArgs: ['-NoProfile', '-NonInteractive', '-Command', 'Update-MpSignature'],
    risk: 'safe',
    requiresElevation: true,
    requiresConfirmation: false,
    timeoutMs: 60000,
    reversible: true,
    description: 'Update Microsoft Defender Signatures',
    verifyMethod: 'defender_status',
  },
  'win.storage.tempclean': {
    platform: 'windows',
    bin: 'powershell',
    fixedArgs: [
      '-NoProfile',
      '-NonInteractive',
      '-Command',
      'Remove-Item -Path "$env:TEMP\\*" -Recurse -Force -ErrorAction SilentlyContinue; Remove-Item -Path "C:\\Windows\\Temp\\*" -Recurse -Force -ErrorAction SilentlyContinue',
    ],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 60000,
    reversible: false,
    description: 'Clean Windows Temporary Files',
    verifyMethod: 'storage_free',
  },
  'win.defrag.trim': {
    platform: 'windows',
    bin: 'defrag',
    fixedArgs: ['C:', '/O'],
    risk: 'safe',
    requiresElevation: true,
    requiresConfirmation: false,
    timeoutMs: 120000,
    reversible: true,
    description: 'Optimize & TRIM Volume C:',
    verifyMethod: 'none',
  },
  'win.service.toggle': {
    platform: 'windows',
    bin: 'powershell',
    fixedArgs: ['-NoProfile', '-NonInteractive', '-Command'],
    parameterSchema: {
      serviceName: { type: 'string', pattern: '^[a-zA-Z0-9_-]+$' },
      action: { type: 'enum', values: ['Start-Service', 'Stop-Service', 'Restart-Service'] },
    },
    risk: 'advanced',
    requiresElevation: true,
    requiresConfirmation: true,
    timeoutMs: 30000,
    reversible: true,
    description: 'Manage Windows Service State',
    verifyMethod: 'service_status',
  },
  'win.startup.toggle': {
    platform: 'windows',
    bin: 'powershell',
    fixedArgs: ['-NoProfile', '-NonInteractive', '-Command'],
    parameterSchema: {
      itemName: { type: 'string', pattern: '^[a-zA-Z0-9 _.-]+$' },
      enable: { type: 'boolean' },
    },
    risk: 'moderate',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 15000,
    reversible: true,
    description: 'Toggle Windows Startup Application',
    verifyMethod: 'startup_status',
  },

  // ── macOS Commands ──────────────────────────────────────────────────────────
  'mac.brew.update': {
    platform: 'macos',
    bin: 'brew',
    fixedArgs: ['update'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 120000,
    reversible: true,
    description: 'Update Homebrew Catalog',
    verifyMethod: 'brew_status',
  },
  'mac.brew.upgrade': {
    platform: 'macos',
    bin: 'brew',
    fixedArgs: ['upgrade'],
    risk: 'moderate',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 300000,
    reversible: true,
    description: 'Upgrade Installed Homebrew Formulae & Casks',
    verifyMethod: 'brew_status',
  },
  'mac.brew.cleanup': {
    platform: 'macos',
    bin: 'brew',
    fixedArgs: ['cleanup', '-s'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 60000,
    reversible: false,
    description: 'Clean Homebrew Download Cache',
    verifyMethod: 'storage_free',
  },
  'mac.softwareupdate.check': {
    platform: 'macos',
    bin: 'softwareupdate',
    fixedArgs: ['-l'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 60000,
    reversible: true,
    description: 'Check macOS Software Updates',
    verifyMethod: 'softwareupdate_status',
  },
  'mac.diskutil.verify': {
    platform: 'macos',
    bin: 'diskutil',
    fixedArgs: ['verifyVolume', '/'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 180000,
    reversible: true,
    description: 'Verify APFS Boot Volume Integrity',
    verifyMethod: 'diskutil_status',
  },
  'mac.diskutil.trim': {
    platform: 'macos',
    bin: 'diskutil',
    fixedArgs: ['apfs', 'trim'],
    risk: 'advanced',
    requiresElevation: true,
    requiresConfirmation: true,
    timeoutMs: 120000,
    reversible: true,
    description: 'Dispatch APFS Container TRIM',
    verifyMethod: 'none',
  },
  'mac.tmutil.thin': {
    platform: 'macos',
    bin: 'tmutil',
    fixedArgs: ['thinlocalsnapshots', '/', '10000000000', '4'],
    risk: 'advanced',
    requiresElevation: true,
    requiresConfirmation: true,
    timeoutMs: 180000,
    reversible: false,
    description: 'Thin Local Time Machine Snapshots',
    verifyMethod: 'snapshot_status',
  },
  'mac.flushdns': {
    platform: 'macos',
    bin: 'dscacheutil',
    fixedArgs: ['-flushcache'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 15000,
    reversible: true,
    description: 'Flush macOS DNS Cache',
    verifyMethod: 'none',
  },
  'mac.spctl.status': {
    platform: 'macos',
    bin: 'spctl',
    fixedArgs: ['--status'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 10000,
    reversible: true,
    description: 'Check Gatekeeper Status',
    verifyMethod: 'spctl_status',
  },
  'mac.purge.ram': {
    platform: 'macos',
    bin: '/usr/bin/purge',
    fixedArgs: [],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 30000,
    reversible: true,
    description: 'Purge Inactive RAM & Memory Caches',
    verifyMethod: 'none',
  },
  'mac.coreaudio.reset': {
    platform: 'macos',
    bin: '/usr/bin/killall',
    fixedArgs: ['-9', 'coreaudiod'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 15000,
    reversible: true,
    description: 'Restart macOS CoreAudio Daemon',
    verifyMethod: 'none',
  },
  'mac.qlmanage.rebuild': {
    platform: 'macos',
    bin: '/usr/bin/qlmanage',
    fixedArgs: ['-r', 'cache'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 15000,
    reversible: true,
    description: 'Rebuild QuickLook & Thumbnail Caches',
    verifyMethod: 'none',
  },
  'mac.brew.doctor': {
    platform: 'macos',
    bin: 'brew',
    fixedArgs: ['doctor'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 60000,
    reversible: true,
    description: 'Run Homebrew Diagnostic Health Check',
    verifyMethod: 'brew_status',
  },
  'mac.brew.autoremove': {
    platform: 'macos',
    bin: 'brew',
    fixedArgs: ['autoremove'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 120000,
    reversible: true,
    description: 'Autoremove Orphaned Homebrew Dependencies',
    verifyMethod: 'brew_status',
  },
  'mac.simctl.clean': {
    platform: 'macos',
    bin: '/usr/bin/xcrun',
    fixedArgs: ['simctl', 'delete', 'unavailable'],
    risk: 'safe',
    requiresElevation: false,
    requiresConfirmation: false,
    timeoutMs: 60000,
    reversible: false,
    description: 'Delete Unavailable iOS Simulator Runtimes',
    verifyMethod: 'storage_free',
  },
};

