import { useState } from 'react';
import { Activity, ArrowRight, CheckCircle2, ChevronRight, Cpu, Download, HardDrive, Play, Shield, Sparkles, Terminal, Wifi, Wrench } from 'lucide-react';
import type { RunMode, SystemInfo, RunSummary } from '../types';
import { usePlatform } from '../platform';
import InspectorModal, { type InspectorData } from './InspectorModal';

interface Props { onStart:(mode?:RunMode)=>void; systemInfo:SystemInfo; summary:RunSummary|null; lastRunTimestamp?:string|null; backendOnline:boolean; onNavigateTab?:(tab:string)=>void; }
const value=(v:unknown,s='')=>v===null||v===undefined||v===''||(typeof v==='number'&&!Number.isFinite(v))?'UNAVAILABLE':`${v}${s}`;
const pct=(v:number|null)=>v===null?'UNAVAILABLE':`${v}%`;

export default function LandingHero({onStart,systemInfo,summary,lastRunTimestamp,backendOnline,onNavigateTab}:Props){
 const {config}=usePlatform(); const [inspect,setInspect]=useState<InspectorData|null>(null); const live=backendOnline;
 const cpu=live&&Number.isFinite(systemInfo.cpuUsage)?systemInfo.cpuUsage:null; const mem=live&&Number.isFinite(systemInfo.memoryUsage)?systemInfo.memoryUsage:null; const total=live&&Number.isFinite(systemInfo.totalDiskGB)?systemInfo.totalDiskGB:null; const free=live&&Number.isFinite(systemInfo.freeDiskGB)?systemInfo.freeDiskGB:null;
 const used=total!==null&&free!==null&&total>0?Math.round(((total-free)/total)*100):null; const health=summary?.healthScore??null;
 const open=(title:string,category:string,details:{label:string,value:unknown}[],action?:{label:string,onClick:()=>void})=>setInspect({title,category,badge:backendOnline?'LIVE':'UNAVAILABLE',subtitle:backendOnline?'Observed from the local telemetry backend.':'Telemetry backend is unavailable.',dataSource:'/api/sysinfo',evidenceQuality:backendOnline?'Observed':'Unavailable',freshness:backendOnline?'Live':'Unavailable',details:details.map(d=>({label:d.label,value:value(d.value)})),actionButton:action});
 const cards=[
  {title:'System Health',icon:Shield,tab:'diagnostics',details:[['Health Score',health===null?'NOT MEASURED':`${health}%`],['CPU',pct(cpu)],['Memory',pct(mem)],['Disk Used',pct(used)]],primary:health===null?'NOT MEASURED':`${health}/100`},
  {title:'Resources',icon:Cpu,tab:'performance',details:[['Processor',live?systemInfo.processor:null],['CPU',pct(cpu)],['Memory',pct(mem)],['Temperature',live?(systemInfo.cpuTempFormatted||'UNAVAILABLE'):null],['RAM',live?value(systemInfo.ramGB,' GB'):null]],primary:pct(cpu)},
  {title:'Storage',icon:HardDrive,tab:'storage',details:[['Free',value(free,' GB')],['Total',value(total,' GB')],['Used',pct(used)],['Last Reclaim',summary?.spaceReclaimed===null||summary?.spaceReclaimed===undefined?'NOT MEASURED':`${summary.spaceReclaimed} MB`]],primary:value(free,' GB')},
 ];
 return <div className="relative z-10 max-w-[1600px] mx-auto px-4 sm:px-6 py-6 sm:py-8 space-y-6"><InspectorModal data={inspect} onClose={()=>setInspect(null)}/>
  <header className="flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div className="flex items-center gap-4"><img src="/logo.png" alt="Win/Mac Suite" className="w-16 h-16 object-contain"/><div><div className="flex flex-wrap gap-2 mb-2"><span className="pill bg-blue-500/10 text-blue-500 border-blue-500/25"><Sparkles size={12}/> Evidence-based telemetry</span><span className="pill">{backendOnline?'Backend connected':'Backend unavailable'}</span></div><h1 className="text-hero font-extrabold" style={{color:'var(--color-ink)'}}>{config.productName}</h1><p className="text-sm" style={{color:'var(--color-ink-3)'}}>{config.tagline} · {value(live?systemInfo.os:null)}</p></div></div><div className="flex gap-2"><button type="button" onClick={()=>onStart('Safe')} className="btn btn-primary cursor-pointer"><Terminal size={15}/> Launch Maintenance</button></div></header>
  {summary&&<section className="card p-4 flex flex-col sm:flex-row justify-between gap-4"><button type="button" onClick={()=>onNavigateTab?.('reports')} className="flex items-center gap-3 text-left cursor-pointer"><CheckCircle2 size={20}/><div><p className="text-xs font-bold">Previous run</p><p className="text-sm font-semibold">{summary.passedSections} of {summary.totalSections} phases passed · {value(summary.totalUpdated)} verified results</p><p className="text-[11px]" style={{color:'var(--color-ink-4)'}}>{lastRunTimestamp?new Date(lastRunTimestamp).toLocaleString():'Timestamp unavailable'}</p></div></button><div className="flex gap-2">{onNavigateTab&&<button type="button" onClick={()=>onNavigateTab('reports')} className="btn btn-secondary text-xs cursor-pointer">View report <ArrowRight size={13}/></button>}<button type="button" onClick={()=>onStart('Safe')} className="btn btn-primary text-xs cursor-pointer">Run again</button></div></section>}
  <div className="grid grid-cols-12 gap-4">{cards.map(c=><button key={c.title} type="button" onClick={()=>open(c.title,'Live System Telemetry',c.details.map(([label,v])=>({label,value:v})),{label:`Open ${c.tab}`,onClick:()=>onNavigateTab?.(c.tab)})} className="card card-hover p-5 col-span-12 lg:col-span-4 text-left cursor-pointer"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold" style={{color:'var(--color-ink)'}}>{c.title}</h2><p className="text-xs" style={{color:'var(--color-ink-4)'}}>Observed data only</p></div><c.icon size={20}/></div><div className="text-3xl font-extrabold mt-5" style={{color:'var(--color-ink)'}}>{c.primary}</div><div className="mt-4 space-y-2">{c.details.slice(0,3).map(([label,v])=><div key={label} className="flex justify-between text-xs"><span style={{color:'var(--color-ink-4)'}}>{label}</span><span className="font-mono font-bold" style={{color:'var(--color-ink)'}}>{v}</span></div>)}</div></button>)}
   <section className="card p-5 col-span-12 lg:col-span-8"><div className="flex items-center justify-between mb-4"><div><h2 className="text-lg font-bold">Quick Actions</h2><p className="text-xs" style={{color:'var(--color-ink-4)'}}>Open the real maintenance workflow.</p></div><Wrench size={20}/></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{(config.quickActions||[]).map(q=><button type="button" key={q.id} onClick={()=>onStart(q.mode)} className="rounded-2xl border p-4 text-left cursor-pointer"><Sparkles size={16}/><p className="font-bold text-sm mt-2">{q.label}</p><p className="text-[11px] mt-1">{q.desc}</p><ChevronRight size={12} className="mt-2"/></button>)}</div><div className="flex flex-wrap gap-2 mt-4"><button type="button" onClick={()=>onStart('ScanOnly')} className="btn btn-secondary text-xs cursor-pointer"><Play size={13}/> Health scan</button><button type="button" onClick={()=>onStart('CleanupOnly')} className="btn btn-secondary text-xs cursor-pointer"><HardDrive size={13}/> Storage cleanup</button>{onNavigateTab&&<button type="button" onClick={()=>onNavigateTab('reports')} className="btn btn-ghost text-xs cursor-pointer"><Download size={13}/> Reports</button>}</div></section>
   <button type="button" onClick={()=>open('Network Status','Network Telemetry',[['Connectivity',live?(systemInfo.isOnline===null?'UNAVAILABLE':systemInfo.isOnline?'Online':'Offline'):null],['Host',live?systemInfo.hostName:null],['Platform',live?systemInfo.os:null]],{label:'Open network diagnostics',onClick:()=>onNavigateTab?.('network')})} className="card card-hover p-5 col-span-12 md:col-span-6 text-left cursor-pointer"><Wifi size={20}/><h2 className="text-lg font-bold mt-3">Network</h2><p className="text-2xl font-extrabold mt-2">{live?(systemInfo.isOnline===null?'UNAVAILABLE':systemInfo.isOnline?'Online':'Offline'):'UNAVAILABLE'}</p></button>
   <button type="button" onClick={()=>onNavigateTab?.('graph')} className="card card-hover p-5 col-span-12 md:col-span-6 text-left cursor-pointer"><Activity size={20}/><h2 className="text-lg font-bold mt-3">System Graph</h2><p className="text-xs mt-2" style={{color:'var(--color-ink-3)'}}>Open the graphical view of observed telemetry.</p></button>
  </div>
 </div>;
}
