import { useState, useEffect } from 'react';
import { Sparkles, ToggleLeft, ToggleRight, Search, RefreshCw, FileText, ChevronRight } from 'lucide-react';
import { usePlatform } from '../platform';
import InspectorModal, { type InspectorData } from './InspectorModal';

export default function StartupManager() {
  const { isMac } = usePlatform();
  const [items,setItems]=useState<any[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [inspectItem,setInspectItem]=useState<InspectorData|null>(null); const [actionMsg,setActionMsg]=useState<string|null>(null);
  const fetchStartup=async()=>{setLoading(true);setError(null);try{const res=await fetch('/api/startup-items');if(!res.ok)throw new Error(`Startup items unavailable (HTTP ${res.status})`);const data=await res.json();setItems(Array.isArray(data.list)?data.list:[]);}catch(e:any){setError(e?.message||'Unable to reach startup manager backend.');setItems([]);}finally{setLoading(false);}};
  useEffect(()=>{fetchStartup();},[]);
  const toggleItem=async(item:any)=>{const next=!item.enabled;setError(null);setActionMsg(null);try{const res=await fetch('/api/actions/toggle-startup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemName:item.name,enable:next,confirmed:true})});const data=await res.json().catch(()=>({}));if(!res.ok||data.success!==true)throw new Error(data.error||`Startup change failed (HTTP ${res.status})`);await fetchStartup();setActionMsg(`${next?'Enabled':'Disabled'} ${item.name} — state re-read from the backend.`);}catch(e:any){setError(e?.message||'Unable to change startup item.');}};
  const filtered=items.filter(it=>(it.name||'').toLowerCase().includes(search.toLowerCase())||(it.location||'').toLowerCase().includes(search.toLowerCase()));
  return <div className="relative z-10 max-w-[1600px] mx-auto px-4 sm:px-6 py-6 sm:py-8 space-y-6">
    <InspectorModal data={inspectItem} onClose={()=>setInspectItem(null)} />
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><div className="inline-flex items-center gap-2 mb-2"><span className="pill bg-blue-500/10 text-blue-500 border-blue-500/25"><Sparkles size={12}/> Startup &amp; Background Items Manager</span></div><h1 className="text-hero font-extrabold tracking-tight" style={{color:'var(--color-ink)'}}>Startup &amp; Background Items Manager</h1><p className="mt-1 text-[14px]" style={{color:'var(--color-ink-3)'}}>{isMac?'Audit Login Items, LaunchAgents, and LaunchDaemons.':'Audit Windows Startup Applications, Registry Run Keys, and background services.'}</p></div><button type="button" onClick={fetchStartup} disabled={loading} className="btn btn-ghost text-xs cursor-pointer"><RefreshCw size={13} className={loading?'animate-spin-smooth':''}/><span>Refresh Startup List</span></button></div>
    {error&&<div className="p-3 rounded-xl bg-red-500/10 border border-red-500/25 text-xs text-red-500">{error}</div>}{actionMsg&&<div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/25 text-xs text-emerald-500">✓ {actionMsg}</div>}
    <div className="card p-4"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none"/><input type="text" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search startup items..." className="field pl-9 py-2 text-xs"/></div></div>
    <div className="card divide-y overflow-hidden">{filtered.map(item=><div key={item.id} onClick={()=>setInspectItem({title:item.name,category:item.type||(isMac?'LaunchAgent':'Startup App'),badge:item.impact?`${item.impact} Boot Impact`:'Observed',subtitle:`Location: ${item.location||'UNAVAILABLE'}`,details:[{label:'Item Name',value:item.name},{label:'Why Is This Running?',value:item.whyIsItRunning||'UNAVAILABLE'},{label:'Configuration Path',value:item.path||item.location||'UNAVAILABLE',isCode:true},{label:'Initialization State',value:item.enabled===true?'Enabled on Boot':item.enabled===false?'Disabled':'UNAVAILABLE'}],actionButton:{label:item.enabled===true?'Disable Temporarily':'Enable Item',onClick:()=>toggleItem(item)}})} className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 transition-colors hover:bg-slate-500/10 cursor-pointer"><div className="flex items-start gap-3 min-w-0"><div className="p-2 rounded-xl shrink-0 mt-0.5 border"><FileText size={16}/></div><div className="min-w-0"><p className="text-sm font-bold truncate" style={{color:'var(--color-ink)'}}>{item.name}</p><p className="text-xs mt-1" style={{color:'var(--color-ink-3)'}}>{item.whyIsItRunning||'UNAVAILABLE'}</p><p className="text-[10px] font-mono mt-0.5 truncate" style={{color:'var(--color-ink-4)'}}>{item.location||'UNAVAILABLE'}</p></div></div><div className="flex items-center gap-3 shrink-0"><button type="button" onClick={e=>{e.stopPropagation();toggleItem(item)}} className="flex items-center gap-2 px-3 py-1.5 rounded-xl border text-xs font-bold cursor-pointer">{item.enabled===true?<ToggleRight size={18}/>:<ToggleLeft size={18}/>}<span>{item.enabled===true?'Enabled':item.enabled===false?'Disabled':'Unavailable'}</span></button><ChevronRight size={14}/></div></div>)}{!loading&&!filtered.length&&!error&&<div className="p-8 text-center text-sm text-slate-400">No startup items found.</div>}</div>
  </div>;
}
