import { useState } from 'react';
import { motion } from 'framer-motion';
import { Monitor, Cpu, HardDrive, Wifi, WifiOff, Clock, MemoryStick, Activity, Apple } from 'lucide-react';
import type { SystemInfo, RunMode } from '../types';
import { usePlatform } from '../platform';
import InspectorModal, { type InspectorData } from './InspectorModal';

interface Props { systemInfo:SystemInfo; selectedMode?:RunMode; live?:boolean; }
const value=(v:unknown,s='')=>v===null||v===undefined||v===''?'UNAVAILABLE':`${v}${s}`;
function Bar({label,value:maxValue,max,unit,color,onClick}:{label:string;value:number|null;max:number;unit:string;color:string;onClick?:()=>void}){const pct=maxValue===null?0:Math.min(Math.max(maxValue/max*100,0),100);return <button type="button" onClick={onClick} className="w-full space-y-1.5 text-left cursor-pointer"><div className="flex justify-between text-[12px]"><span className="font-semibold">{label}</span><span className="font-mono font-bold">{value(maxValue,unit)}</span></div><div className="h-2 rounded-full overflow-hidden" style={{backgroundColor:'var(--color-surface-2)'}}>{maxValue!==null&&<motion.div initial={{scaleX:0}} animate={{scaleX:pct/100}} className="h-full rounded-full origin-left" style={{backgroundColor:color}}/>}</div></button>}
export default function SystemInfoPanel({systemInfo,live=false}:Props){const{config,isMac}=usePlatform();const[inspect,setInspect]=useState<InspectorData|null>(null);const online=systemInfo.isOnline;const rows=[
 {icon:isMac?Apple:Monitor,k:'Host',v:value(systemInfo.hostName)},
 {icon:Cpu,k:isMac?'Processor':'Processor',v:value(systemInfo.processor)},
 {icon:MemoryStick,k:'Memory',v:value(systemInfo.ramGB,' GB RAM')},
 {icon:HardDrive,k:'Storage',v:systemInfo.totalDiskGB!==null&&systemInfo.freeDiskGB!==null?`${systemInfo.freeDiskGB} GB free / ${systemInfo.totalDiskGB} GB`:'UNAVAILABLE'},
 {icon:Clock,k:'Uptime',v:value(systemInfo.uptime)},
 ];
 const inspectRow=(k:string)=>{setInspect({title:k,category:'Live System Telemetry',badge:live?'Observed':'Unavailable',subtitle:live?'Values below come from the local telemetry service.':'No live telemetry is currently available.',dataSource:'/api/sysinfo',evidenceQuality:live?'Observed':'Unavailable',freshness:live?'Live':'Unavailable',details:[{label:'Hostname',value:value(systemInfo.hostName)},{label:'Operating System',value:value(systemInfo.os)},{label:'Processor',value:value(systemInfo.processor)},{label:'RAM',value:value(systemInfo.ramGB,' GB')},{label:'Free Disk',value:value(systemInfo.freeDiskGB,' GB')},{label:'Total Disk',value:value(systemInfo.totalDiskGB,' GB')},{label:'CPU Load',value:value(systemInfo.cpuUsage,'%')},{label:'Memory Usage',value:value(systemInfo.memoryUsage,'%')},{label:'CPU Temperature',value:systemInfo.cpuTempFormatted||'UNAVAILABLE'}]});};
 return <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="card p-5 sm:p-6"><InspectorModal data={inspect} onClose={()=>setInspect(null)}/><div className="flex items-center justify-between pb-4 mb-4 border-b" style={{borderColor:'var(--color-line)'}}><div className="flex items-center gap-2"><Activity size={16} className="text-blue-500"/><h3 className="text-[13px] font-bold uppercase tracking-wider">{config.productName} Telemetry</h3>{live&&<span className="pill">Live</span>}</div><button type="button" onClick={()=>inspectRow('Network Connectivity')} className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold border cursor-pointer">{online===null?<><WifiOff size={11}/> UNAVAILABLE</>:online?<><Wifi size={11}/> Online</>:<><WifiOff size={11}/> Offline</>}</button></div><div className="space-y-2">{rows.map(r=><button type="button" key={r.k} onClick={()=>inspectRow(r.k)} className="w-full flex items-center gap-3 p-2.5 rounded-xl text-left border cursor-pointer" style={{backgroundColor:'var(--color-surface-2)',borderColor:'var(--color-line)'}}><r.icon size={15}/><div className="min-w-0"><span className="block text-[11px] uppercase" style={{color:'var(--color-ink-4)'}}>{r.k}</span><span className="font-mono font-bold truncate block" style={{color:'var(--color-ink)'}}>{r.v}</span></div></button>)}</div><div className="mt-5 pt-4 border-t space-y-3" style={{borderColor:'var(--color-line)'}}><Bar label="CPU Load" value={systemInfo.cpuUsage} max={100} unit="%" color="#2563eb" onClick={()=>inspectRow('CPU Load')}/><Bar label="Memory Usage" value={systemInfo.memoryUsage} max={100} unit="%" color="#7c3aed" onClick={()=>inspectRow('Memory Usage')}/></div></motion.div>;
}
