import type { PlatformConfig, MaintenancePhaseTemplate, QuickAction } from './types';

export const MACOS_PHASES: MaintenancePhaseTemplate[] = [
  {
    id: 'packages',
    number: 1,
    title: 'Package Updates & CLI Environments',
    description: 'Homebrew formulae & casks, MacPorts, Python Pip3, Node NPM globals',
    icon: 'Package',
    category: 'packages',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'mac.brew.upgrade',
    targetTools: ['brew', 'port', 'pip3', 'npm'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- Homebrew and CLI environments updated',
    verificationSummary: 'Brew update/upgrade cycle completed; outdated formulae updated.',
    details: { 'Homebrew Formulae': 'Synchronized', 'Casks': 'Checked', 'Pip3 Packages': 'Optimal', 'NPM Globals': 'Verified' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Running brew update to sync Homebrew core and cask taps...' },
      { time: '', level: 'SUCCESS', message: '[brew] Homebrew formulae database updated.' },
      { time: '', level: 'INFO', message: 'Checking outdated Homebrew packages (brew upgrade)...' },
      { time: '', level: 'SUCCESS', message: '[brew] All installed CLI tools and GUI casks are up to date.' },
      { time: '', level: 'INFO', message: 'Auditing Python 3 pip and Node.js global modules...' },
      { time: '', level: 'SUCCESS', message: '[OK] CLI development environments up to date.' },
    ],
  },
  {
    id: 'security-status',
    number: 2,
    title: 'Apple Security Signatures & Gatekeeper',
    description: 'XProtect definitions, MRT malware removal definitions, Gatekeeper status',
    icon: 'ShieldCheck',
    category: 'security',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'mac.spctl.status',
    targetTools: ['XProtect', 'MRT', 'Gatekeeper', 'spctl'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 2,
    maxDuration: 4,
    successResult: 'DONE -- Security Definitions Up-To-Date',
    verificationSummary: 'XProtect Remediator signatures verified; Gatekeeper policy is active.',
    details: { 'XProtect Config': 'v5280', 'Remediator': 'Active', 'Gatekeeper': 'Enabled (spctl: assessments enabled)' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Checking Apple XProtect and XProtect Remediator definitions...' },
      { time: '', level: 'INFO', message: 'Verifying Gatekeeper assessment policy (spctl --status)...' },
      { time: '', level: 'SUCCESS', message: '[OK] XProtect signatures current; Gatekeeper protection is active.' },
    ],
  },
  {
    id: 'macos-updates',
    number: 3,
    title: 'macOS Software Update (System Patches)',
    description: 'Core macOS updates and security response patches via softwareupdate',
    icon: 'Download',
    category: 'system',
    riskLevel: 'safe',
    requiresElevation: true,
    allowedCommandId: 'mac.softwareupdate.check',
    targetTools: ['softwareupdate'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 4,
    maxDuration: 8,
    successResult: 'DONE -- macOS Software Update Evaluated',
    verificationSummary: 'Queried Apple Software Update Catalog; verified current macOS patch level.',
    details: { 'Software Catalog': 'Apple Production', 'Rapid Security Response': 'Verified', 'Core System': 'Up-to-date' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Querying Apple Software Update servers (softwareupdate -l)...' },
      { time: '', level: 'INFO', message: 'Checking for Rapid Security Responses (RSR) and system updates...' },
      { time: '', level: 'SUCCESS', message: '[OK] No pending mandatory system patches required.' },
    ],
  },
  {
    id: 'app-updates',
    number: 4,
    title: 'Mac App Store Applications',
    description: 'Mac App Store app updates via mas CLI and app worker',
    icon: 'Store',
    category: 'store',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'mac.system_profiler.apps',
    targetTools: ['system_profiler SPApplicationsDataType', 'mas CLI'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 2,
    maxDuration: 5,
    successResult: 'DONE -- Mac App Store Apps Verified',
    verificationSummary: 'Checked Mac App Store receipts; all purchased applications are current.',
    details: { 'Mac App Store': 'Connected', 'App Receipts': 'Validated' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Connecting to Mac App Store worker (mas outdated)...' },
      { time: '', level: 'INFO', message: 'Synchronizing receipts with Apple ID store account...' },
      { time: '', level: 'SUCCESS', message: '[OK] All Mac App Store applications are up to date.' },
    ],
  },
  {
    id: 'hardware-diag',
    number: 5,
    title: 'Hardware & Apple Silicon Diagnostics',
    description: 'IOKit device scan, thermal pressure state, and battery health audit',
    icon: 'Cpu',
    category: 'hardware',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'mac.system_profiler.hardware',
    targetTools: ['system_profiler', 'pmset -g batt', 'thermal status'],
    skipModes: ['CleanupOnly'],
    minDuration: 3,
    maxDuration: 5,
    successResult: 'DONE -- 0 Hardware Anomalies Detected',
    verificationSummary: 'Apple Silicon thermal state nominal; battery health normal; no IOKit faults.',
    details: { 'Thermal Pressure': 'Nominal (Green)', 'Battery Condition': 'Normal (100% Health)', 'IOKit Scan': 'Clean' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Querying IOKit registry for connected peripherals and buses...' },
      { time: '', level: 'INFO', message: 'Auditing Apple Silicon thermal state and PMU power parameters...' },
      { time: '', level: 'SUCCESS', message: '[OK] System thermals and hardware components operating within normal bounds.' },
    ],
  },
  {
    id: 'background-items',
    number: 6,
    title: 'Background Items & LaunchDaemons Audit',
    description: 'Audit LaunchDaemons, LaunchAgents, Login Items, and background extensions',
    icon: 'HardDrive',
    category: 'drivers',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'mac.launchctl.list',
    targetTools: ['launchctl', 'sfltool', 'Login Items API'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- Background Services Audited',
    verificationSummary: 'System & User LaunchAgents verified; 0 orphan daemon services found.',
    details: { 'User LaunchAgents': 'Verified', 'System Daemons': 'Active', 'Login Items': 'Audited' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Scanning ~/Library/LaunchAgents and /Library/LaunchDaemons...' },
      { time: '', level: 'INFO', message: 'Verifying signed background helper tools and login extensions...' },
      { time: '', level: 'SUCCESS', message: '[OK] Background item registry is clean and structured.' },
    ],
  },
  {
    id: 'apfs-integrity',
    number: 7,
    title: 'APFS Volume Integrity & File System Check',
    description: 'APFS container verification, First Aid scan, and SIP status validation',
    icon: 'FileCheck',
    category: 'integrity',
    riskLevel: 'moderate',
    requiresElevation: true,
    allowedCommandId: 'mac.diskutil.verify',
    targetTools: ['diskutil verifyVolume', 'csrutil status', 'fsck_apfs'],
    skipModes: ['Quick', 'CleanupOnly'],
    minDuration: 4,
    maxDuration: 9,
    successResult: 'DONE -- APFS Integrity Verified (No Errors)',
    verificationSummary: 'APFS container metadata, object map, and snapshot trees verified.',
    details: { 'APFS Container': 'Verified', 'System Integrity Protection': 'Enabled (csrutil)', 'Object Map': 'Healthy' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Executing APFS volume integrity scan (diskutil verifyVolume /)...' },
      { time: '', level: 'INFO', message: 'Validating APFS object map, inode tree, and volume extents...' },
      { time: '', level: 'SUCCESS', message: '[OK] The volume / was found to be in good health.' },
      { time: '', level: 'INFO', message: 'Verifying System Integrity Protection (SIP)...' },
      { time: '', level: 'SUCCESS', message: '[OK] System Integrity Protection status: enabled.' },
    ],
  },
  {
    id: 'cache-cleanup',
    number: 8,
    title: 'System & User Library Cache Purge',
    description: '~/Library/Caches, Xcode DerivedData, CocoaPods, and Homebrew download cache',
    icon: 'FolderSync',
    category: 'cleanup',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'mac.brew.cleanup',
    targetTools: ['~/Library/Caches', 'brew cleanup', 'DerivedData'],
    skipModes: ['ScanOnly'],
    minDuration: 3,
    maxDuration: 7,
    successResult: 'DONE -- 2.3 GB Cache Space Reclaimed',
    verificationSummary: 'Purged stale application caches, QuickLook thumbnails, and brew staging files.',
    details: { 'User Caches': 'Purged', 'Homebrew Cache': 'Cleaned (brew cleanup)', 'QuickLook Cache': 'Reset' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Scanning user application cache directory (~/Library/Caches)...' },
      { time: '', level: 'INFO', message: 'Executing Homebrew cache cleanup (brew cleanup -s)...' },
      { time: '', level: 'SUCCESS', message: '[OK] 2.3 GB of stale application cache payloads purged.' },
    ],
  },
  {
    id: 'timemachine-snapshots',
    number: 9,
    title: 'Time Machine Snapshot Thinning & Purgeable Space',
    description: 'Thin local APFS backup snapshots and reclaim purgeable system storage',
    icon: 'Trash',
    category: 'cleanup',
    riskLevel: 'advanced',
    requiresElevation: true,
    allowedCommandId: 'mac.tmutil.thin',
    targetTools: ['tmutil thinlocalsnapshots', 'APFS purgeable space'],
    skipModes: ['ScanOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- 3.1 GB Purgeable Storage Reclaimed',
    verificationSummary: 'Thinned redundant local Time Machine snapshots on APFS boot container.',
    details: { 'APFS Snapshots': 'Thinned', 'Purgeable Space': 'Reclaimed', 'Boot Volume': 'Optimized' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Scanning APFS local snapshot store (tmutil listlocalsnapshots /)...' },
      { time: '', level: 'INFO', message: 'Thinning dated local backup snapshots to reclaim purgeable space...' },
      { time: '', level: 'SUCCESS', message: '[OK] Local APFS snapshots optimized; 3.1 GB storage released to volume pool.' },
    ],
  },
  {
    id: 'memory-trim',
    number: 10,
    title: 'Storage Optimization & APFS TRIM',
    description: 'SSD block TRIM dispatch, font cache refresh, and inactive memory consolidation',
    icon: 'Gauge',
    category: 'optimization',
    riskLevel: 'safe',
    requiresElevation: true,
    allowedCommandId: 'mac.diskutil.trim',
    targetTools: ['diskutil apfs trim', 'atsutil databases', 'dscacheutil -flushcache'],
    skipModes: ['ScanOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- Storage & Memory Optimized',
    verificationSummary: 'SSD storage blocks trimmed; font cache and Directory Services cache flushed.',
    details: { 'SSD Block TRIM': 'Dispatched', 'Directory Cache': 'Flushed', 'Memory Pressure': 'Nominal' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Dispatching SSD TRIM commands across APFS container (diskutil apfs trim)...' },
      { time: '', level: 'INFO', message: 'Flushing macOS Directory Services lookup cache (dscacheutil -flushcache)...' },
      { time: '', level: 'SUCCESS', message: '[OK] APFS volume blocks trimmed and memory subsystem consolidated.' },
    ],
  },
];

export const MACOS_QUICK_ACTIONS: QuickAction[] = [
  { id: 'quick', icon: 'Zap', label: 'Quick Update', accent: '#06b6d4', desc: 'Homebrew packages & XProtect status', mode: 'Quick' },
  { id: 'health-scan', icon: 'Shield', label: 'Health Scan', accent: '#3b82f6', desc: 'APFS First Aid & hardware status', mode: 'ScanOnly' },
  { id: 'full-update', icon: 'Download', label: 'Full Update', accent: '#8b5cf6', desc: 'Standard comprehensive Mac update cycle', mode: 'Safe' },
  { id: 'deep-clean', icon: 'HardDrive', label: 'Deep Clean', accent: '#f59e0b', desc: 'Cache purge & Time Machine snapshot thinning', mode: 'CleanupOnly' },
];

export const MACOS_CONFIG: PlatformConfig = {
  platform: 'macos',
  productName: 'MacSuite',
  version: '16.1.1',
  subtitle: 'macOS System Maintenance & Diagnostics',
  tagline: 'Intelligent, capability-aware Mac optimization & performance engine',
  osFamily: 'macOS',
  badgeIcon: 'Apple',
  accentColor: '#06b6d4',
  packageManagerName: 'Homebrew / MacPorts / mas',
  securityEngineName: 'XProtect & Gatekeeper',
  integrityToolName: 'APFS First Aid & SIP',
  systemUpdateName: 'macOS Software Update',
  storeName: 'Mac App Store',
  storageOptimizationName: 'APFS TRIM & Snapshot Thinning',
  quickActions: MACOS_QUICK_ACTIONS,
  phases: MACOS_PHASES,
  modeDescriptions: {
    Safe: {
      label: 'Standard Full Update',
      description: 'Package updates, APFS volume checks, and safe cache maintenance. Recommended for routine care.',
      icon: 'Shield',
      color: 'blue',
    },
    Quick: {
      label: 'Quick Update',
      description: 'Homebrew and XProtect updates. Skips deep APFS disk checks for quick turnaround.',
      icon: 'Zap',
      color: 'cyan',
    },
    Aggressive: {
      label: 'Deep Maintenance',
      description: 'Full updates, Time Machine snapshot thinning, deep cache purge, and volume TRIM with confirmation.',
      icon: 'Flame',
      color: 'orange',
    },
    ScanOnly: {
      label: 'Health Scan Only',
      description: 'Hardware diagnostics + APFS First Aid verification. Non-destructive.',
      icon: 'Search',
      color: 'purple',
    },
    CleanupOnly: {
      label: 'Cleanup Only',
      description: 'Caches, local Time Machine snapshot thinning, and temp cleanup. No package updates.',
      icon: 'Trash2',
      color: 'green',
    },
    Custom: {
      label: 'Custom Maintenance',
      description: 'Select specific individual maintenance phases based on system capabilities.',
      icon: 'Layers',
      color: 'indigo',
    },
  },
  riskGuidelines: {
    safe: {
      label: 'Safe',
      description: 'Non-destructive operation. Safe to run anytime.',
      color: '#16a34a',
      badge: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/25',
    },
    moderate: {
      label: 'Moderate',
      description: 'Deep cache purge or APFS integrity scan. Modifies temporary system state.',
      color: '#d97706',
      badge: 'bg-amber-500/10 text-amber-500 border-amber-500/25',
    },
    advanced: {
      label: 'Advanced',
      description: 'System-level operation requiring explicit confirmation.',
      color: '#dc2626',
      badge: 'bg-red-500/10 text-red-500 border-red-500/25',
    },
  },
};
