import type { PlatformConfig, MaintenancePhaseTemplate, QuickAction } from './types';

export const WINDOWS_PHASES: MaintenancePhaseTemplate[] = [
  {
    id: 'apps',
    number: 1,
    title: 'Application & Package Updates',
    description: 'Winget, Chocolatey, Scoop, Python Pip, Node NPM',
    icon: 'Package',
    category: 'packages',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'win.winget.upgrade',
    targetTools: ['Winget', 'Chocolatey', 'Scoop', 'Pip', 'NPM'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- Packages audited and updated',
    verificationSummary: 'CLI package managers scanned; available package updates applied.',
    details: { 'Winget Status': 'Active', 'Chocolatey': 'Checked', 'Pip': 'Up-to-date', 'Scoop': 'Indexed' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Scanning for Winget application updates...' },
      { time: '', level: 'SUCCESS', message: '[winget] Package catalog synchronized.' },
      { time: '', level: 'INFO', message: 'Checking Chocolatey package manager...' },
      { time: '', level: 'SUCCESS', message: '[choco] Installed packages are up to date.' },
      { time: '', level: 'INFO', message: 'Verifying Python Pip and NPM global packages...' },
      { time: '', level: 'SUCCESS', message: '[OK] CLI package environments updated successfully.' },
    ],
  },
  {
    id: 'defender',
    number: 2,
    title: 'Microsoft Defender Security Signatures',
    description: 'Virus, spyware, and network protection definitions refresh',
    icon: 'ShieldCheck',
    category: 'security',
    riskLevel: 'safe',
    requiresElevation: true,
    allowedCommandId: 'win.defender.update',
    targetTools: ['MpCmdRun', 'Update-MpSignature'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 2,
    maxDuration: 4,
    successResult: 'DONE -- Signatures Up-To-Date',
    verificationSummary: 'Defender engine version verified; definition database refreshed.',
    details: { 'Engine': '1.1.24090.2', 'Signature Version': 'Latest Verified', 'Realtime Protection': 'Enabled' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Connecting to Microsoft Security Intelligence update service...' },
      { time: '', level: 'INFO', message: 'Downloading signature differential payload...' },
      { time: '', level: 'SUCCESS', message: '[OK] Microsoft Defender signatures updated via Update-MpSignature.' },
    ],
  },
  {
    id: 'windows-update',
    number: 3,
    title: 'Windows Update (OS Patches)',
    description: 'Cumulative security & quality patches via PSWindowsUpdate',
    icon: 'Download',
    category: 'system',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'win.update.audit',
    targetTools: ['PSWindowsUpdate', 'Windows Update Agent'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 4,
    maxDuration: 8,
    successResult: 'DONE -- System Patches Evaluated',
    verificationSummary: 'Queried Microsoft Update catalog; validated current patch level.',
    details: { 'Security Patches': 'Installed', 'Quality Rollups': 'Verified', 'Catalog Sync': 'Online' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Querying Windows Update API for pending KB patches...' },
      { time: '', level: 'INFO', message: 'Evaluating cumulative security updates and servicing stack...' },
      { time: '', level: 'SUCCESS', message: '[OK] Windows Update evaluation completed.' },
    ],
  },
  {
    id: 'store',
    number: 4,
    title: 'Microsoft Store Applications',
    description: 'UWP & Store app package update worker',
    icon: 'Store',
    category: 'store',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'win.store.scan',
    targetTools: ['Winget msstore', 'MDM Worker'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 2,
    maxDuration: 5,
    successResult: 'DONE -- Store Apps Verified',
    verificationSummary: 'Microsoft Store catalog refreshed and pending app packages synced.',
    details: { 'Store Manifest': 'Synchronized', 'App Status': 'Up-to-date' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Scanning for Microsoft Store application updates via Winget source...' },
      { time: '', level: 'INFO', message: 'Triggered Store application update worker...' },
      { time: '', level: 'SUCCESS', message: '[OK] Microsoft Store apps verified.' },
    ],
  },
  {
    id: 'hardware',
    number: 5,
    title: 'Hardware Driver Diagnostics & PnP Scan',
    description: 'Device Manager error codes & Plug-and-Play enumeration',
    icon: 'Cpu',
    category: 'hardware',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'win.hardware.scan',
    targetTools: ['PnP Util', 'Device Manager API', 'WMI Win32_PnPEntity'],
    skipModes: ['CleanupOnly'],
    minDuration: 3,
    maxDuration: 5,
    successResult: 'DONE -- 0 Hardware Faults Detected',
    verificationSummary: 'All PCI, USB, ACPI and Display devices reported Code 0 (Working properly).',
    details: { 'PnP Devices': 'Scanned', 'Device Error Codes': 'None', 'Bus Enumeration': 'Clean' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Enumerating PnP hardware devices and querying ConfigManager codes...' },
      { time: '', level: 'INFO', message: 'Auditing USB, Display, Audio, and Network controllers...' },
      { time: '', level: 'SUCCESS', message: '[OK] All hardware controllers responding normally.' },
    ],
  },
  {
    id: 'drivers',
    number: 6,
    title: 'Optional & Driver Quality Updates',
    description: 'Manufacturer driver packages and optional quality fixes',
    icon: 'HardDrive',
    category: 'drivers',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'win.drivers.audit',
    targetTools: ['Windows Update Driver Catalog', 'pnputil'],
    skipModes: ['ScanOnly', 'CleanupOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- Drivers Validated',
    verificationSummary: 'Checked vendor catalog; current driver packages are optimal.',
    details: { 'Chipset': 'Verified', 'Graphics Driver': 'Optimal', 'Audio': 'Stable' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Querying Microsoft Driver Catalog for optional driver releases...' },
      { time: '', level: 'INFO', message: 'Verifying installed OEM driver signatures...' },
      { time: '', level: 'SUCCESS', message: '[OK] Hardware drivers are up to date.' },
    ],
  },
  {
    id: 'integrity',
    number: 7,
    title: 'System File Integrity Verification',
    description: 'SFC /scannow & DISM Component Store verification',
    icon: 'FileCheck',
    category: 'integrity',
    riskLevel: 'moderate',
    requiresElevation: true,
    allowedCommandId: 'win.sfc',
    targetTools: ['sfc', 'dism'],
    skipModes: ['Quick', 'CleanupOnly'],
    minDuration: 4,
    maxDuration: 9,
    successResult: 'DONE -- Integrity Verified (No Violations)',
    verificationSummary: 'System File Checker and DISM reported protected files in good condition.',
    details: { 'SFC Scan': 'Clean', 'DISM Health': 'Healthy', 'Component Store': 'Verified' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Initiating System File Checker verification (sfc /scannow)...' },
      { time: '', level: 'INFO', message: 'Checking Windows Protected System Files against pristine hashes...' },
      { time: '', level: 'SUCCESS', message: '[OK] Windows Resource Protection did not find any integrity violations.' },
      { time: '', level: 'INFO', message: 'Verifying Component Store health via DISM...' },
      { time: '', level: 'SUCCESS', message: '[OK] DISM Component Store health is Healthy.' },
    ],
  },
  {
    id: 'update-cache',
    number: 8,
    title: 'Update Cache & Component Cleanup',
    description: 'SoftwareDistribution cache & DISM component store cleanup',
    icon: 'FolderSync',
    category: 'cleanup',
    riskLevel: 'moderate',
    requiresElevation: true,
    allowedCommandId: 'win.dism.cleanup',
    targetTools: ['DISM /StartComponentCleanup', 'wuauserv cache'],
    skipModes: ['ScanOnly'],
    minDuration: 3,
    maxDuration: 7,
    successResult: 'DONE -- 1.4 GB Component Space Reclaimed',
    verificationSummary: 'SoftwareDistribution download artifacts and superseded components cleared.',
    details: { 'SoftwareDistribution': 'Purged', 'Superseded Updates': 'Cleaned' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Stopping Windows Update staging service temporarily...' },
      { time: '', level: 'INFO', message: 'Clearing superseded update payloads from C:\\Windows\\SoftwareDistribution...' },
      { time: '', level: 'SUCCESS', message: '[OK] Update cache cleaned; Windows Update service resumed.' },
    ],
  },
  {
    id: 'disk-cleanup',
    number: 9,
    title: 'Disk & System Cache Cleanup',
    description: 'Temp files, crash dumps, WER logs, DNS resolver cache, Recycle Bin',
    icon: 'Trash',
    category: 'cleanup',
    riskLevel: 'safe',
    requiresElevation: false,
    allowedCommandId: 'win.storage.tempclean',
    targetTools: ['Cleanmgr', 'Temp purger', 'ipconfig /flushdns'],
    skipModes: ['ScanOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- 1.7 GB Junk Reclaimed',
    verificationSummary: 'User temp folders, crash memory dumps, and DNS cache emptied.',
    details: { 'User Temp': 'Cleaned', 'Crash Dumps': 'Emptied', 'DNS Cache': 'Flushed', 'Recycle Bin': 'Processed' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Scanning %TEMP% and system temporary staging directories...' },
      { time: '', level: 'INFO', message: 'Purging Windows Error Reporting (WER) logs and crash memory dumps...' },
      { time: '', level: 'INFO', message: 'Flushing Windows DNS Resolver Cache (ipconfig /flushdns)...' },
      { time: '', level: 'SUCCESS', message: '[OK] Disk cleanup finished (1.7 GB reclaimed).' },
    ],
  },
  {
    id: 'optimization',
    number: 10,
    title: 'Drive Optimization & Storage Sense',
    description: 'SSD TRIM, defrag re-trim, Storage Sense, startup services audit',
    icon: 'Gauge',
    category: 'optimization',
    riskLevel: 'safe',
    requiresElevation: true,
    allowedCommandId: 'win.defrag.trim',
    targetTools: ['defrag /O', 'fsutil behavior', 'Storage Sense'],
    skipModes: ['ScanOnly'],
    minDuration: 3,
    maxDuration: 6,
    successResult: 'DONE -- Storage Volumes Optimized',
    verificationSummary: 'SSD TRIM commands dispatched across all detected NTFS volumes.',
    details: { 'SSD TRIM': 'Dispatched', 'Slab Consolidation': 'Complete', 'Storage Sense': 'Triggered' },
    logs: () => [
      { time: '', level: 'INFO', message: 'Dispatching SSD TRIM commands across active disk volumes (defrag /O)...' },
      { time: '', level: 'INFO', message: 'Consolidating storage slabs and verifying filesystem health...' },
      { time: '', level: 'SUCCESS', message: '[OK] All volume blocks trimmed and optimized.' },
    ],
  },
];

export const WINDOWS_QUICK_ACTIONS: QuickAction[] = [
  { id: 'quick', icon: 'Zap', label: 'Quick Update', accent: '#06b6d4', desc: 'Winget apps & Defender definitions', mode: 'Quick' },
  { id: 'health-scan', icon: 'Shield', label: 'Health Scan', accent: '#3b82f6', desc: 'SFC & DISM integrity checks', mode: 'ScanOnly' },
  { id: 'full-update', icon: 'Download', label: 'Full Update', accent: '#8b5cf6', desc: 'Standard comprehensive update cycle', mode: 'Safe' },
  { id: 'deep-clean', icon: 'HardDrive', label: 'Deep Clean', accent: '#f59e0b', desc: 'SoftwareDistribution & junk cleanup', mode: 'CleanupOnly' },
];

export const WINDOWS_CONFIG: PlatformConfig = {
  platform: 'windows',
  productName: 'WinSuite',
  version: '6.3.0',
  subtitle: 'Windows System Maintenance & Diagnostics',
  tagline: 'Intelligent, capability-aware PC optimization & health management',
  osFamily: 'Windows',
  badgeIcon: 'Monitor',
  accentColor: '#2563eb',
  packageManagerName: 'Winget / Chocolatey / Scoop',
  securityEngineName: 'Microsoft Defender',
  integrityToolName: 'SFC & DISM',
  systemUpdateName: 'Windows Update (KB)',
  storeName: 'Microsoft Store',
  storageOptimizationName: 'SSD TRIM & Storage Sense',
  quickActions: WINDOWS_QUICK_ACTIONS,
  phases: WINDOWS_PHASES,
  modeDescriptions: {
    Safe: {
      label: 'Standard Full Update',
      description: 'Full updates, standard integrity checks, safe cache cleanup. Recommended for regular maintenance.',
      icon: 'Shield',
      color: 'blue',
    },
    Quick: {
      label: 'Quick Update',
      description: 'Application, Store, and Defender updates. Skips SFC/DISM for maximum speed.',
      icon: 'Zap',
      color: 'cyan',
    },
    Aggressive: {
      label: 'Deep Maintenance',
      description: 'Full updates, component cleanup, prefetch clear, and volume TRIM with confirmation.',
      icon: 'Flame',
      color: 'orange',
    },
    ScanOnly: {
      label: 'Health Scan Only',
      description: 'Hardware diagnostics + SFC & DISM integrity scan. Non-destructive.',
      icon: 'Search',
      color: 'purple',
    },
    CleanupOnly: {
      label: 'Cleanup Only',
      description: 'Disk, update cache, crash dumps, and temp cleanup. No software updates.',
      icon: 'Trash2',
      color: 'green',
    },
    Custom: {
      label: 'Custom Maintenance',
      description: 'Select specific individual maintenance phases based on system capabilities.',
      icon: 'Layers',
      color: 'indigo',
    },
  },
  riskGuidelines: {
    safe: {
      label: 'Safe',
      description: 'Non-destructive operation. Safe to run anytime.',
      color: '#16a34a',
      badge: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/25',
    },
    moderate: {
      label: 'Moderate',
      description: 'Deep file integrity or component purge. Low risk, but modifies system caches.',
      color: '#d97706',
      badge: 'bg-amber-500/10 text-amber-500 border-amber-500/25',
    },
    advanced: {
      label: 'Advanced',
      description: 'System-level operation requiring explicit confirmation.',
      color: '#dc2626',
      badge: 'bg-red-500/10 text-red-500 border-red-500/25',
    },
  },
};
